@startuml

skinparam noteBorderColor #5a5a5a
skinparam noteBackgroundColor #005aa1
skinparam noteFontColor white


skinparam sequence {
  ArrowColor #005aa1
  ParticipantBackgroundColor #005aa1
  ParticipantFontName Apex
  ParticipantFontSize 17
  ParticipantFontColor White
  ParticipantBorderColor #5a5a5a

  ActorBorderColor #5a5a5a
  ActorBackgroundColor #005aa1
  ActorFontColor #005aa1
  ActorFontSize 17
  ActorFontName Apex


}


participant G5
participant TestSequencer
actor Handler

== Power on ==

G5 -> TestSequencer: State: NotReady
note over G5: G5 initializes


== Test sequence loop start ==

Handler -> G5: Put DUT(s) in

Handler -> G5: POST URL/api/state {"value": "Engage"}


note over G5: Slide or hatch starts to close

G5 -> TestSequencer: State: Ready

note over TestSequencer, G5
Testing can be started with some limitation,
robot cannot be moved and there is no RF/audio shielding
end note

G5 -> TestSequencer: State: Ready

note over TestSequencer, G5: Slide or hatch is fully closed and all test features are available.

TestSequencer -> TestSequencer: POST URL/api/state {"value": "Release"}

G5 -> TestSequencer: State: NotReady

Handler -> G5: Takes DUT(s) out

== End of the test sequence loop ==


@enduml