@startuml
skinparam state {
  StartColor #005aa1
  EndColor Red
  BackgroundColor #005aa1
  BackgroundColor<<Warning>> Olive
  BorderColor #5a5a5a
  FontName Apex
  AttributeFontColor White
  FontColor White
  ArrowColor #005aa1
}

[*] --> NotReady
NotReady -> ReadyForEngage
ReadyForEngage -> Ready
Ready -> NotReady

Ready: M Test Box is ready for testing.
Ready: All signals are connected.

Closing: M Test Box is closing.
Closing: Some test activities can
Closing: be started now but there
Closing: might be limitations on
Closing: connected signals and
Closing: machine is not RF or audio
Closing: shielded.

ReadyForEngage: DUT(s) is placed to M Test Box
ReadyForEngage: by an operator or by a handler
ReadyForEngage: machine and slide is closed.
ReadyForEngage: Engage command can
ReadyForEngage: be given through API.

NotReady: M Test Box is not ready
NotReady: for testing.
@enduml