
@startuml

skinparam noteBorderColor #5a5a5a
skinparam noteBackgroundColor #005aa1
skinparam noteFontColor white


skinparam sequence {
  ArrowColor #005aa1
  ParticipantBackgroundColor #005aa1
  ParticipantFontName Apex
  ParticipantFontSize 17
  ParticipantFontColor White
  ParticipantBorderColor #5a5a5a

  ActorBorderColor #5a5a5a
  ActorBackgroundColor #005aa1
  ActorFontColor #005aa1
  ActorFontSize 17
  ActorFontName Apex


}


participant "M Test Box"
participant TestSequencer
participant Handler

== Power on ==


"M Test Box" -> TestSequencer: State: NotReady

note over "M Test Box": M Test Box initializes

"M Test Box" -> Handler : HandlerState: NotReady_Closed

Handler -> "M Test Box": POST URL/api/state {"value": "Open"}

== Test sequence loop start ==

"M Test Box" -> Handler : HandlerState: ReadyToReceive

Handler -> "M Test Box": Puts DUT(s) in

Handler -> "M Test Box": POST URL/api/state {"value": "Close"}

"M Test Box" -> Handler : HandlerState: NotReady

note over "M Test Box": Slide closes

"M Test Box" -> Handler : HandlerState: NotReady_Closed

"M Test Box" -> TestSequencer: State: ReadyForEngage

TestSequencer -> "M Test Box": POST URL/api/state {"value": "Engage"}

note over "M Test Box": M Test Box engages DUT

"M Test Box" -> TestSequencer: State: Ready

note over TestSequencer, "M Test Box": M Test Box is ready for testing

TestSequencer -> "M Test Box": POST URL/api/state {"value": "Release"}

note over "M Test Box": M Test Box releases DUT

"M Test Box" -> TestSequencer: State: NotReady

"M Test Box" -> Handler : HandlerState: ReadyToDispatch

Handler -> "M Test Box": Takes DUT(s) out

== End of the test sequence loop ==

@enduml
